const express=require("express")
const jobController=require("../controllers/jobController")
const verifyJWT=require("../middleware/verifyJWT")
const router=express.Router()
router.use(verifyJWT)
router.get("/",jobController.getAllJobs)
router.post("/",jobController.addJob)
router.put("/",jobController.updateJob)
router.delete("/",jobController.deleteJob)
module.exports=router