const express=require("express")
const questionController=require("../controllers/questionController")
const verifyJWT=require("../middleware/verifyJWT")
const verifyAdmin=require("../middleware/verifyAdmin")
const router=express.Router()
router.use(verifyJWT)
router.get("/",questionController.getAllQuestions)
router.post("/",verifyAdmin,questionController.addQuestion)
router.put("/",verifyAdmin,questionController.updateQuestion)
router.delete("/",verifyAdmin,questionController.deleteQuestion)
module.exports=router